### ISSUE TITLE
ENH: Use more numpy/scipy for math

### ISSUE THREAD

**Issue by dohmatob** [tansey/pycfr#3]
Most operations on arrays, and other similar math seem to be done manually. We should use numpy/scipy for that.

**Comment by tansey** [comment]
I definitely agree that in general numpy/scipy for scientific code is more appropriate. However, the choice to not use them was intentional. This is not a package designed for speed, but rather one designed to be used as a learning framework that can be easily digested by people looking to implement their own CFR algorithm or variant.

If you'd like to fork the project and make a vectorized version, I think that's a great idea.
